apiVersion : v1
kind : PersistentVolume
metadata :
   name : mypv
spec :
  capacity :
    storage : 500Mi
  accessModes :
    - ReadWriteOnce
  persistentVolumeReclaimPolicy : Retain
  storageClassName : local-storage
  local : 
    path : /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - node1

---

apiVersion : v1
kind : PersistentVolumeClaim
metadata : 
  name : mypvc
spec :
  resources :
    requests :
      storage : 300Mi
  accessModes :
    - ReadWriteOnce
  storageClassName : local-storage

---

apiVersion : v1
kind : Pod
metadata :
  name : mypod
spec :
  nodeSelector:
    kubernetes.io/hostname : node1
  containers:
  - name: www
    image: nginx:alpine
    resources:
      requests:
        memory: "500Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: www
    volumeMounts:
      - name: www-store
        mountPath: /usr/share/nginx/html
  volumes :
    - name : www-store
      persistentVolumeClaim :
        claimName : mypvc