apiVersion : v1
kind : PersistentVolume
metadata :
  name : pv1
spec :
  capacity :
    storage : 200Mi
  accessModes :
    - ReadWriteOnce
  persistentVolumeReclaimPolicy : Retain
  storageClassName : local-storage
  hostPath :
    path : /mnt/data

---

apiVersion : v1
kind : PersistentVolumeClaim
metadata :
  name : pvc1
spec :
  storageClassName : local-storage
  resources :
    requests:
      storage : 200Mi
  accessModes : 
    - ReadWriteOnce

---

apiVersion : apps/v1
kind : Deployment
metadata :
  name : dep1
spec :
  replicas : 1
  selector :
    matchLabels :
      app.k8s.io/name : nginx-server
  template :
    metadata :
      name : pod1
      labels :
        app.k8s.io/name : nginx-server
    spec :
      containers :
        - name : nginx
          image : nginx
          ports :
            - containerPort : 80
              name : www
          volumeMounts :
            - name : www-store
              mountPath : /usr/share/nginx/html
      volumes :
        - name : www-store
          persistentVolumeClaim :
            claimName : pvc1